<?php
header('Content-Type: application/json');
echo json_encode([
    ["hsn_code" => "1234", "description" => "Cotton Yarn", "gst_rate" => "5", "category" => "Textiles"],
    ["hsn_code" => "5678", "description" => "Plastic Items", "gst_rate" => "18", "category" => "Plastics"],
    ["hsn_code" => "0101", "description" => "Horses, asses, mules and hinnies, live", "gst_rate" => "0", "category" => "Live animals"],
    ["hsn_code" => "0201", "description" => "Meat of bovine animals, fresh or chilled", "gst_rate" => "12", "category" => "Meat products"],
    ["hsn_code" => "0401", "description" => "Milk and cream, not concentrated", "gst_rate" => "0", "category" => "Dairy products"],
    ["hsn_code" => "0402", "description" => "Milk and cream, concentrated or with sweetener", "gst_rate" => "5", "category" => "Dairy products"],
    ["hsn_code" => "0601", "description" => "Bulbs, tubers, roots and the like", "gst_rate" => "5", "category" => "Horticultural products"],
    ["hsn_code" => "0701", "description" => "Potatoes, fresh or chilled", "gst_rate" => "5", "category" => "Vegetables"],
    ["hsn_code" => "0801", "description" => "Coconuts, Brazil nuts and cashew nuts, fresh or dried", "gst_rate" => "5", "category" => "Dry fruits & nuts"],
    ["hsn_code" => "1001", "description" => "Wheat and meslin", "gst_rate" => "0", "category" => "Cereals"],
    ["hsn_code" => "1006", "description" => "Rice", "gst_rate" => "0", "category" => "Cereals"],
    ["hsn_code" => "1511", "description" => "Palm oil and its fractions", "gst_rate" => "5", "category" => "Edible oils"],
    ["hsn_code" => "1701", "description" => "Cane or beet sugar and chemically pure sucrose", "gst_rate" => "5", "category" => "Sugar"],
    ["hsn_code" => "1905", "description" => "Bread, pastry, cakes and similar items", "gst_rate" => "18", "category" => "Bakery items"],
    ["hsn_code" => "2106", "description" => "Protein concentrates and textured protein substances", "gst_rate" => "18", "category" => "Food preparations"],
    ["hsn_code" => "2201", "description" => "Water, including mineral waters and aerated waters", "gst_rate" => "18", "category" => "Beverages"],
    ["hsn_code" => "2202", "description" => "Non-alcoholic beverages (excluding fruit juices)", "gst_rate" => "28", "category" => "Soft drinks"],
    ["hsn_code" => "2402", "description" => "Cigarettes containing tobacco", "gst_rate" => "28", "category" => "Tobacco products"],
    ["hsn_code" => "2710", "description" => "Petroleum oils and oils obtained from bituminous minerals", "gst_rate" => "18", "category" => "Petroleum products"],
    ["hsn_code" => "3004", "description" => "Medicaments for therapeutic or prophylactic uses", "gst_rate" => "12", "category" => "Pharmaceuticals"],
    ["hsn_code" => "3401", "description" => "Soaps and organic surface-active products", "gst_rate" => "18", "category" => "Toiletries"],
    ["hsn_code" => "3926", "description" => "Plastic articles nes", "gst_rate" => "18", "category" => "Plastic products"],
    ["hsn_code" => "4011", "description" => "New pneumatic tyres, of rubber", "gst_rate" => "28", "category" => "Automotive parts"],
    ["hsn_code" => "4819", "description" => "Cartons, boxes and cases of paper/paperboard", "gst_rate" => "18", "category" => "Packaging material"],
    ["hsn_code" => "6203", "description" => "Men’s or boys’ suits, ensembles, jackets", "gst_rate" => "5", "category" => "Apparel"],
    ["hsn_code" => "6204", "description" => "Women’s or girls’ suits, ensembles, jackets", "gst_rate" => "5", "category" => "Apparel"],
    ["hsn_code" => "7102", "description" => "Diamonds, whether or not worked, but not mounted", "gst_rate" => "0.25", "category" => "Gems & Jewelry"],
    ["hsn_code" => "7108", "description" => "Gold (including gold plated with platinum), unwrought or semi-manufactured", "gst_rate" => "3", "category" => "Precious metals"],
    ["hsn_code" => "8528", "description" => "Television sets", "gst_rate" => "18", "category" => "Electronics"],
    ["hsn_code" => "8703", "description" => "Motor cars and other motor vehicles for transport", "gst_rate" => "28", "category" => "Automobiles"],
    ["hsn_code" => "9403", "description" => "Furniture and parts thereof", "gst_rate" => "18", "category" => "Furniture"],
    ["hsn_code" => "9997", "description" => "Services not elsewhere specified", "gst_rate" => "18", "category" => "General Services"]
]);
